version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres